### ISSUE TITLE
build_and_

### ISSUE THREAD

**Issue by coneheadusa** [google/deepvariant#134]
I'm trying to build deepvariant on debian_version stretch/sid,  3.10.0-327.3.1.el7.x86_64 #1 SMP Wed Dec 9 14:09:15 UTC 2015, and the build_and_test script is failing.

The build-prereq.sh command runs successfully; however, build_and_test.sh throws this error:
  In file included from external/htslib/hts.c:45:0:
  external/htslib/hts_internal.h:31:32: fatal error: textutils_internal.h: No such file or directory

Yet the file is found here:
 .cache/bazel/_bazel_root/5b3dfb1a5a17f553ec98d93bc2cea6e8/execroot/com_google_deepvariant/external/htslib/textutils_internal.h

I get the same error if I try to build on CentOS  7.2.1511 (Core).    Please advise.

**Comment by coneheadusa** [comment]
I tracked the problem down to building with bazel 0.19.0 rather that 0.15.0.
