### ISSUE TITLE
Build and test works, binaries do not

### ISSUE THREAD

**Issue by KBT59** [google/deepvariant#47]
I'm unfamiliar with the bazel build environment. After a successful build with tensorflow-gpu, all tests passed, but on attempting to run a binary from bazel-bin I see

2018-02-05 11:14:37.628020: I tensorflow/core/platform/s3/aws_logging.cc:53] Initializing Curl library
Traceback (most recent call last):
  File "/home2/bradBuild/deepvariant/bazel-bin/deepvariant/make_examples.runfiles/genomics/deepvariant/make_examples.py", line 1105, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 118, in run
    argv = flags.FLAGS(_sys.argv if argv is None else argv, known_only=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/flags.py", line 112, in __call__
    return self.__dict__['__wrapped'].__call__(*args, **kwargs)
TypeError: __call__() got an unexpected keyword argument 'known_only'

**Comment by rpoplin** [comment]
I wonder if there is an issue somehow with how you are building with tensorflow-gpu. What commands did you use to build it? We think this should work with tensorflow-gpu==1.4.

Here is what I did to try it out:

git clone https://github.com/google/deepvariant.git

#edit settings.sh so that DV_GPU_BUILD=1 and DV_INSTALL_GPU_DRIVERS=1

./build-prereq.sh
./build_release_binaries.sh

then ran a test command with the quickstart testdata:

python deepvariant/bazel-bin/deepvariant/make_examples.zip \
--mode calling \
--ref "${REF}" \
--reads "${BAM}" \
--regions "chr20:10,000,000-10,010,000" \
--examples "${OUTPUT_DIR}/examples.tfrecord.gz"

which executes as expected.

**Comment by KBT59** [comment]
Hello Ryan,

I built on an Ubuntu 16 system with CUDA-9.0, CUDNN version 7, tensorflow-gpu installed via tf-nightly-GPU using the last build available of 1.5 (it depends on CUDA-9.0).  As I mentioned, build_and_test.sh showed success, running all tests successfully.

I can install CUDA 8, CUDNN 6 and try again.

Brad Thomas

**Comment by rpoplin** [comment]
Unfortunately DeepVariant isn't yet compatible with TensorFlow version 1.5 so I think you'll need to install tensorflow-gpu version 1.4 for this to work. In our build script we do this with 
sudo -H pip install --upgrade 'tensorflow-gpu==1.4'

**Comment by KBT59** [comment]
Hello Ryan,

I was able to build successfully using CUDA 8.0, cudnn 6, and tensorflow-gpu 1.4.  I ran the WES example. That went fine.

Questions:  what is the minimum allele frequency deepvariant will call?   Is there a version contemplated that will do matched tumor/normal pairs? Unmatched pairs (as with a “pooled” normal)?

Thanks,
Brad Thomas

**Comment by rpoplin** [comment]
Great to hear.

There are minimum allele fractions that are used to generate candidate variants here (https://github.com/google/deepvariant/blob/r0.5/deepvariant/make_examples.py#L165), you'll likely want to lower those thresholds for your use case. For the model itself, there is no explicit allele fraction, but keep in mind that the model was trained to predict the diploid genotype states of {hom ref, het, and hom var} so things that are lower allele fraction will likely be classified as 0/0 by the model. We don't currently have a version that does somatic variant calling.

**Comment by KBT59** [comment]
Hello Ryan,


Thanks for the information. We have about 500 curated vcf on a gene panel we use here. I will try to create a model for that panel.  We want variants as low as 1%.  Have you tried something similar?


Best,

Brad Thomas

________________________________

**Comment by rpoplin** [comment]
Sounds fun! I haven't tried something similar yet. One thing to maybe keep in mind, for 1% allele fraction that means you probably have depth >100x coverage, so you might find that you want to change the default height of the pileup tensors which is set at 100. Here is the flag for that in make_examples: https://github.com/google/deepvariant/blob/r0.5/deepvariant/make_examples.py#L177

**Comment by KBT59** [comment]
pileup_image_height?  Yes, our depths can be as much as a few thousands.  I haven’t looked at the data set yet, but that’s common.

Brad Thomas

**Comment by rpoplin** [comment]
Yeah, the input to the CNN is a pileup tensor. Check out here for some more info: https://github.com/google/deepvariant#about-deepvariant

It would be interesting to train a new model for your particular data type.
