### ISSUE TITLE
Does it build with Python3?

### ISSUE THREAD

**Issue by logust79** [google/deepvariant#31]
On Ubuntu 16.04 LTS, when I tried to build it from source with Python 3.6.2, it failed to compile `bazel-out/k8-py3-opt/genfiles/deepvariant/core/python/hts_verbose.cc`, and the error was `hts_verbose.cc:134:143: error: 'Py_InitModule3' was not declared in this scope`. After some investigations and it seems to be an incompatible issue with Python 3. 

The relatively full stack is here:

(14:05:26) ERROR: xx/git/deepvariant/deepvariant/core/python/BUILD:174:1: C++ compilation of rule '//deepvariant/core/python:hts_verbose_cclib' failed (Exit 1): gcc failed: error executing command 
  (cd xx/.cache/bazel/xx/7e4d04a878642732d9b8bb40a634229e/execroot/genomics && \
  exec env - \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=xx/anaconda/envs/Python36/bin/python \
    PYTHON_LIB_PATH=xx/anaconda/envs/Python36/lib/python3.6/site-packages \
    TF_NEED_CUDA=0 \
    TF_NEED_OPENCL_SYCL=0 \
  /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections -DGEMMLOWP_ALLOW_SLOW_SCALAR_FALLBACK -Wno-maybe-uninitialized -Wno-unused-function -msse4.1 -msse4.2 -mavx -O3 '-std=c++0x' -MD -MF bazel-out/k8-py3-opt/bin/deepvariant/core/python/_objs/hts_verbose_cclib/deepvariant/core/python/hts_verbose.d '-frandom-seed=bazel-out/k8-py3-opt/bin/deepvariant/core/python/_objs/hts_verbose_cclib/deepvariant/core/python/hts_verbose.o' -iquote . -iquote bazel-out/k8-py3-opt/genfiles -iquote external/htslib -iquote bazel-out/k8-py3-opt/genfiles/external/htslib -iquote external/bazel_tools -iquote bazel-out/k8-py3-opt/genfiles/external/bazel_tools -iquote external/clif -iquote bazel-out/k8-py3-opt/genfiles/external/clif -iquote external/local_config_python -iquote bazel-out/k8-py3-opt/genfiles/external/local_config_python -iquote external/protobuf_archive -iquote bazel-out/k8-py3-opt/genfiles/external/protobuf_archive -isystem external/htslib/htslib/htslib_1_6 -isystem bazel-out/k8-py3-opt/genfiles/external/htslib/htslib/htslib_1_6 -isystem external/htslib -isystem bazel-out/k8-py3-opt/genfiles/external/htslib -isystem external/bazel_tools/tools/cpp/gcc3 -isystem external/local_config_python/python_include -isystem bazel-out/k8-py3-opt/genfiles/external/local_config_python/python_include -isystem external/protobuf_archive/src -isystem bazel-out/k8-py3-opt/genfiles/external/protobuf_archive/src '-std=c++11' -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c bazel-out/k8-py3-opt/genfiles/deepvariant/core/python/hts_verbose.cc -o bazel-out/k8-py3-opt/bin/deepvariant/core/python/_objs/hts_verbose_cclib/deepvariant/core/python/hts_verbose.o)
bazel-out/k8-py3-opt/genfiles/deepvariant/core/python/hts_verbose.cc: In function 'PyObject* deepvariant_core_python_hts__verbose_clifwrap::Init()':
bazel-out/k8-py3-opt/genfiles/deepvariant/core/python/hts_verbose.cc:134:143: error: 'Py_InitModule3' was not declared in this scope
   PyObject* module = Py_InitModule3("deepvariant.core.python.hts_verbose", Methods, "CLIF-generated module for deepvariant/core/hts_verbose.h");
                                                                                                                                               ^
(14:05:26) INFO: Elapsed time: 4.048s, Critical Path: 1.26s

**Comment by depristo** [comment]
Unfortunately DeepVariant only works with python 2.7 right now. We can look into making this work with Python 3 but it's likely to take a bit of time. How critical is it for you to use python 3? More information will help us prioritize python 3 support.

**Comment by logust79** [comment]
Thank you for your answer. Python 3 is not critical at the moment. I might have missed it but it would be good to mention this in the doc?

**Comment by depristo** [comment]
That's good to know. I'm put in a PR in our internal systems adding a note about Python 2.7 being required. The docs should show up on our next sync to github.

**Comment by logust79** [comment]
Thank you!
