### ISSUE TITLE
#include <optional> error after update from v0.8.0 to v0.9.0

### ISSUE THREAD

**Issue by Stikus** [google/deepvariant#236]
Hello DeepVariant team.

We're trying to use your great tool and I'm creating our own Docker for this.
Yesterday I finally fixed all issues with v0.8.0 version - all tests from build_and_test.sh passed and saw v0.9.0 release happened several days before - I tried to switch to in and get error at build_and_test.sh stage:
```
deepvariant/variant_calling.cc:36:20: fatal error: optional: No such file or directory
 #include <optional>
                    ^
compilation terminated.
```
Looks like you added new include lines in `deepvariant/variant_calling.cc` between releases - [this](https://github.com/google/deepvariant/blob/r0.9/deepvariant/variant_calling.cc#L36) line causing my error.
Can you help me please? Do I need to install some external dependencies or what?

**Comment by pichuan** [comment]
Thank you for reporting the issue.
Can you tell us more about what environment you're building it in? (OS version, gcc version)
I tried build_and_test.sh just now, and didn't see any issue. I'd like to reproduce the error so we can help fix it for your setting.


For example, here is my version:
```
pichuan@pichuan-build:~$ uname -a
Linux pichuan-build 4.15.0-1049-gcp #52-Ubuntu SMP Fri Nov 8 10:30:54 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
pichuan@pichuan-build:~/deepvariant$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial
```

Then I clone our repo:
```
pichuan@pichuan-build:~$ git clone https://github.com/google/deepvariant.git
```
Confirmed it's on r0.9:
```
pichuan@pichuan-build:~$ cd deepvariant/
pichuan@pichuan-build:~/deepvariant$ git branch
* r0.9
```
And then I build:
```
pichuan@pichuan-build:~/deepvariant$ ./build-prereq.sh && ./build_and_test.sh 
```
This completed without an error.

I checked my gcc version:
```
pichuan@pichuan-build:~/deepvariant$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by Stikus** [comment]
Thank you for answer.
We are using Ubuntu 14.04 for our images (yes, still).
```
# uname -a
Linux 417d805a5037 3.10.0-1062.4.1.el7.x86_64 #1 SMP Fri Oct 18 17:15:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
```
root@417d805a5037:/outputs# lsb_release -a
No LSB modules are available.             
Distributor ID: Ubuntu                    
Description:    Ubuntu 14.04.6 LTS        
Release:        14.04                     
Codename:       trusty 
```
```
root@417d805a5037:/outputs# gcc --version                                  
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.4) 4.8.4                                  
Copyright (C) 2013 Free Software Foundation, Inc.                          
This is free software; see the source for copying conditions.  There is NO 
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Maybe we need newer `gcc`?

And we don't clone repos - we download release archives.

**Comment by pichuan** [comment]
@Stikus Hi, I was able to reproduce the issue on Ubuntu 14.
We don't officially support a build on Ubuntu 14, but I'll give it a try and see if I'm able to get it to work. I can give an update later.

One question for you - Can you tell us the reason why you're not using our Docker image, and instead building your own binaries? It'll be useful for us to understand what our users need so we can prioritize the right things. Thank you!

**Comment by pichuan** [comment]
Hi @Stikus , 
actually , it seems like simply removing the line
```
#include <optional>
```
will build.

From the code, we're using "optional" from tensorflow::gtl::optional. So we don't really need the #include here.

I have confirmed that removing this line builds on Ubuntu14.04. Please give that a try. If it doesn't work, let me know.

I will make an internal fix, which will come out in the next release. For now, please make a local edit before you build.

**Comment by Stikus** [comment]
> One question for you - Can you tell us the reason why you're not using our Docker image, and instead building your own binaries? It'll be useful for us to understand what our users need so we can prioritize the right things. Thank you!

We are always creating our own images because we have a lot of preinstalled soft in them and all them start from same instructions. And for full understanding of external programs too.

Thanks for proposal, I'll try to build v0.9.0 without `#include <optional>` and report here.

**Comment by Stikus** [comment]
Thank you for help, with your tweak build and tests passed.
But I get different results on test data - described [here](https://github.com/google/deepvariant/issues/239#issuecomment-558061938).
